/* eslint-disable */
export const PRODUCTS = [
  {
    cat: "Salami & Soppressa", slug: "hot-soppressa", name: "Hot Soppressa",
    sub: "Naturally cured with chilli and fennel. Coarse-cut, traditional southern-Italian style.",
    weight: "1 kg whole", batch: "HS-26-04", image: "/assets/photos/products/hot_soppressa.png",
    description: "Our hot soppressa is made to a traditional southern-Italian recipe passed down from Cham's father. Coarse-cut Australian pork shoulder is blended with cracked fennel seed and dried chilli flakes, then stuffed into natural casings and hung in our curing house for a minimum of eight weeks. The result is a firm, intensely flavoured salami with a slow, building heat that pairs well with aged cheeses and crusty bread.",
    ingredients: "Australian pork (85%), salt, dried chilli flakes, fennel seed, garlic, dextrose, black pepper, starter culture, sodium nitrate.",
    formats: ["250 g retail vacuum pack", "1 kg whole (hospitality)", "Sliced 100 g deli pack"],
    storage: "Refrigerate at 0–4°C. Once opened, consume within 14 days.",
    curing: "Minimum 8 weeks natural air-cured",
    origin: "Lismore, NSW",
  },
  {
    cat: "Salami & Soppressa", slug: "mild-soppressa", name: "Mild Soppressa",
    sub: "The classic Calabrian recipe, made without heat. Slow-cured for ten weeks.",
    weight: "1 kg whole", batch: "MS-26-04", image: "/assets/photos/products/mild_soppressa.png",
    description: "The mild soppressa is Cham's original recipe and the product that started the business. Made without chilli, it lets the quality of the pork and the depth of the cure speak for themselves. Coarse-ground pork with garlic, black pepper, and a touch of white wine, hung for ten full weeks. This is the salami Cham made in his garage in 1985 — the recipe hasn't changed.",
    ingredients: "Australian pork (87%), salt, black pepper, garlic, white wine, dextrose, starter culture, sodium nitrate.",
    formats: ["250 g retail vacuum pack", "1 kg whole (hospitality)", "Sliced 100 g deli pack"],
    storage: "Refrigerate at 0–4°C. Once opened, consume within 14 days.",
    curing: "Minimum 10 weeks natural air-cured",
    origin: "Lismore, NSW",
  },
  {
    cat: "Salami & Soppressa", slug: "traditional-salami", name: "Traditional Salami",
    sub: "House-recipe pork salami. Lightly seasoned, finely-grained. Sliced or whole.",
    weight: "1 kg whole", batch: "TS-26-03", image: "/assets/photos/products/traditional_salami.png",
    description: "Our traditional salami is a finely-grained, lightly seasoned pork salami suited to everyday eating. It's the most versatile product in our range — equally at home on a sandwich, a pizza, or an antipasto board. Finely ground Australian pork seasoned with salt, pepper, and garlic, then cured for six weeks. Available whole or pre-sliced for deli and hospitality.",
    ingredients: "Australian pork (88%), salt, black pepper, garlic, dextrose, starter culture, sodium nitrate.",
    formats: ["1 kg whole", "500 g half", "Sliced 150 g deli pack", "Bulk 5 kg (hospitality)"],
    storage: "Refrigerate at 0–4°C. Once opened, consume within 14 days.",
    curing: "Minimum 6 weeks natural air-cured",
    origin: "Lismore, NSW",
  },
  {
    cat: "Salami & Soppressa", slug: "cacciatore", name: "Cacciatore",
    sub: "Hunter-style salami in a small format. Sized to fit a back pocket. Pack of four.",
    weight: "4 × 80 g", batch: "CC-26-04", image: "/assets/photos/products/cacciatore.png",
    description: "Cacciatore — 'hunter's salami' — is a small-format dried sausage designed to be eaten on the go. Ours are hand-tied, individually cured, and sold in packs of four. They're sized to fit a coat pocket or a lunchbox. Rich, dense, and deeply savoury, with a fine grind and a peppery finish. A favourite with school lunches and hiking packs alike.",
    ingredients: "Australian pork (86%), salt, black pepper, garlic, paprika, fennel seed, dextrose, starter culture, sodium nitrate.",
    formats: ["4 × 80 g retail pack", "20-pack box (hospitality)"],
    storage: "Refrigerate at 0–4°C. Individually sealed — once opened, consume within 7 days.",
    curing: "Minimum 4 weeks natural air-cured",
    origin: "Lismore, NSW",
  },
  {
    cat: "Cured Cuts", slug: "pepperoni", name: "Pepperoni",
    sub: "Hot, oily, paprika-forward. The pizzeria standard, made the proper way.",
    weight: "200 g sliced", batch: "PP-26-04", image: "/assets/photos/products/pepperoni.png",
    description: "Our pepperoni is made for the pizzeria. Smoky, paprika-forward, with a clean heat and an oily cure that crisps beautifully under a broiler. We use a blend of pork and a small percentage of beef for the characteristic texture. Pre-sliced for convenience or available as whole sticks for in-house slicing. Supplied to over sixty pizzerias across NSW.",
    ingredients: "Australian pork (72%), Australian beef (12%), salt, paprika, chilli, garlic, black pepper, dextrose, starter culture, sodium nitrate.",
    formats: ["200 g sliced retail pack", "1.5 kg whole stick (hospitality)", "Pre-sliced 2 kg bulk (hospitality)"],
    storage: "Refrigerate at 0–4°C. Once opened, consume within 10 days.",
    curing: "Minimum 5 weeks smoked and air-cured",
    origin: "Lismore, NSW",
  },
  {
    cat: "Cured Cuts", slug: "pancetta", name: "Pancetta",
    sub: "Belly pork, dry-cured for eight weeks. Available rolled or flat.",
    weight: "200 g", batch: "PA-26-03", image: "/assets/photos/products/pancetta.png",
    description: "Our pancetta is dry-cured pork belly, seasoned with juniper, bay leaf, and black pepper, then hung for eight weeks. Available rolled (arrotolata) for slicing into thin rounds, or flat (stesa) for dicing into lardons. The fat is silky and flavourful — it renders beautifully for pasta, risotto, and any dish where you need a rich, porky base.",
    ingredients: "Australian pork belly (92%), salt, black pepper, juniper berry, bay leaf, garlic, dextrose, sodium nitrate.",
    formats: ["500 g rolled (retail)", "500 g flat (retail)", "2 kg whole slab (hospitality)"],
    storage: "Refrigerate at 0–4°C. Once opened, consume within 14 days.",
    curing: "Minimum 8 weeks dry-cured",
    origin: "Lismore, NSW",
  },
  {
    cat: "Preserved Goods", slug: "pickled-peppers", name: "Pickled Peppers",
    sub: "Long red chillies in a brine of vinegar, salt, and bay leaf.",
    weight: "500 g jar", batch: "PE-26-02", image: "/assets/photos/products/pickled_peppers.png",
    description: "Whole long red chillies pickled in a simple brine of white wine vinegar, salt, and bay leaf. Crunchy, tangy, and gently hot — these are the peppers Cham's family served at every meal in Calabria. Excellent alongside cured meats, on sandwiches, or chopped through a pasta sauce for a vinegary kick.",
    ingredients: "Long red chillies, white wine vinegar, water, salt, bay leaf, garlic.",
    formats: ["330 g glass jar (retail)", "2 L catering jar (hospitality)"],
    storage: "Store in a cool, dry place. Refrigerate after opening. Consume within 4 weeks of opening.",
    curing: "Brined minimum 3 weeks",
    origin: "Lismore, NSW",
  },
  {
    cat: "Preserved Goods", slug: "marinated-artichokes", name: "Marinated Artichokes",
    sub: "Quartered artichoke hearts in olive oil, garlic and parsley.",
    weight: "500 g jar", batch: "AR-26-02", image: "/assets/photos/products/marinated_artichokes.png",
    description: "Quartered artichoke hearts, blanched and marinated in Australian extra-virgin olive oil with garlic, flat-leaf parsley, and a touch of white wine vinegar. Tender, earthy, and rich — ideal for antipasto platters, pizza toppings, or served straight from the jar with good bread. Made in small batches at our Lismore facility.",
    ingredients: "Artichoke hearts (55%), extra-virgin olive oil, white wine vinegar, garlic, flat-leaf parsley, salt, black pepper.",
    formats: ["280 g glass jar (retail)", "2 L catering jar (hospitality)"],
    storage: "Store in a cool, dry place. Refrigerate after opening. Keep submerged in oil. Consume within 3 weeks of opening.",
    curing: "Marinated minimum 2 weeks",
    origin: "Lismore, NSW",
  },
  {
    cat: "Preserved Goods", slug: "giardiniera", name: "Giardiniera",
    sub: "Mixed pickled vegetables — cauliflower, capsicum, carrot, celery.",
    weight: "500 g jar", batch: "GI-26-02", image: "/assets/photos/products/giardiniera.png",
    description: "Our giardiniera is a classic Italian mixed pickle — cauliflower, capsicum, carrot, and celery, cut into bite-sized pieces and pickled in white wine vinegar with oregano and chilli. Bright, crunchy, and versatile. Serve it as a side, pile it on a sandwich, or eat it straight from the jar. A staple of every Italian pantry and a natural partner to everything else we make.",
    ingredients: "Cauliflower, capsicum, carrot, celery, white wine vinegar, water, extra-virgin olive oil, salt, oregano, dried chilli, garlic.",
    formats: ["500 g glass jar (retail)", "2 L catering jar (hospitality)"],
    storage: "Store in a cool, dry place. Refrigerate after opening. Consume within 4 weeks of opening.",
    curing: "Pickled minimum 2 weeks",
    origin: "Lismore, NSW",
  },
  {
    cat: "Preservatives", slug: "sodium-nitrite", name: "Sodium Nitrite",
    sub: "Pink curing salt No. 1. Pre-blended at 6.25% concentration for processed meats.",
    weight: "20 kg pail", batch: "SN-26-03", image: "/assets/photos/products/sodium_nitrite.png",
    description: "Our sodium nitrite is supplied as Pink Curing Salt No. 1 — a pre-blended compound of 6.25% sodium nitrite and 93.75% salt, dyed pink for identification. It is the standard curing agent for colour fixation and microbial control in processed meats including salami, bacon, ham, and other smallgoods. Used at recommended rates, it inhibits Clostridium botulinum and fixes the characteristic cured-meat colour. Supplied in a sealed 20 kg food-grade pail.",
    ingredients: "Salt (93.75%), sodium nitrite (6.25%), FD&C Red No. 3 (trace, for identification).",
    formats: ["20 kg food-grade pail"],
    storage: "Store in a cool, dry place away from direct sunlight. Keep sealed when not in use.",
    curing: "N/A — curing ingredient",
    origin: "Lismore, NSW",
  },
  {
    cat: "Preservatives", slug: "phosphate-blend", name: "Phosphate Blend (STP)",
    sub: "Sodium tripolyphosphate. Improves water retention and texture in meat products.",
    weight: "20 kg pail", batch: "PH-26-02", image: "/assets/photos/products/phosphate_blend.png",
    description: "Sodium tripolyphosphate (STP) is a food-grade phosphate used to improve water retention and texture in injected and tumbled meat products. It increases the pH of meat, allowing proteins to bind more water during processing, resulting in a juicier finished product with better slicing yield. Widely used in ham, bacon, and other brine-injected smallgoods. Supplied in a sealed 20 kg food-grade pail.",
    ingredients: "Sodium tripolyphosphate (100%).",
    formats: ["20 kg food-grade pail"],
    storage: "Store in a cool, dry place. Keep sealed to prevent moisture absorption.",
    curing: "N/A — processing ingredient",
    origin: "Lismore, NSW",
  },
  {
    cat: "Preservatives", slug: "sodium-erythorbate", name: "Sodium Erythorbate",
    sub: "Curing accelerant. Speeds colour development and reduces residual nitrite.",
    weight: "20 kg pail", batch: "SE-26-03", image: "/assets/photos/products/sodium_erythorbate.png",
    description: "Sodium erythorbate is a curing accelerant used alongside sodium nitrite in processed meat manufacture. It speeds the conversion of nitrite to nitric oxide, accelerating colour development and reducing the level of residual nitrite in the finished product. This results in a more consistent cure colour and a cleaner label. Essential for high-throughput production where curing time is limited. Supplied in a sealed 20 kg food-grade pail.",
    ingredients: "Sodium erythorbate (100%).",
    formats: ["20 kg food-grade pail"],
    storage: "Store in a cool, dry place away from direct sunlight. Keep sealed when not in use.",
    curing: "N/A — curing accelerant",
    origin: "Lismore, NSW",
  },
  {
    cat: "Preservatives", slug: "potassium-sorbate", name: "Potassium Sorbate",
    sub: "Inhibits yeast and mould in cured, pickled, and acidified products. Odourless.",
    weight: "20 kg pail", batch: "KS-26-02", image: "/assets/photos/products/potassium_sorbate.png",
    description: "Potassium sorbate is an odourless, highly soluble preservative that inhibits yeast and mould growth in cured, pickled, and acidified food products. It is effective across a broad pH range and is commonly used in brines, marinades, and surface treatments for cured meats. Its neutral taste and high solubility make it one of the most versatile antimicrobial preservatives available. Supplied in a sealed 20 kg food-grade pail.",
    ingredients: "Potassium sorbate (100%).",
    formats: ["20 kg food-grade pail"],
    storage: "Store in a cool, dry place. Keep sealed to prevent moisture absorption.",
    curing: "N/A — antimicrobial preservative",
    origin: "Lismore, NSW",
  },
  {
    cat: "Preservatives", slug: "sodium-benzoate", name: "Sodium Benzoate",
    sub: "Broad-spectrum antimicrobial for acidified and brined products. Effective below pH 4.5.",
    weight: "20 kg pail", batch: "SB-26-01", image: "/assets/photos/products/sodium_benzoate.png",
    description: "Sodium benzoate is a broad-spectrum antimicrobial preservative most effective in acidified and brined products with a pH below 4.5. It inhibits the growth of bacteria, yeast, and mould in pickled vegetables, acidified sauces, and brined products. A staple preservative in commercial food manufacturing, valued for its reliability and regulatory acceptance worldwide. Supplied in a sealed 20 kg food-grade pail.",
    ingredients: "Sodium benzoate (100%).",
    formats: ["20 kg food-grade pail"],
    storage: "Store in a cool, dry place. Keep sealed when not in use.",
    curing: "N/A — antimicrobial preservative",
    origin: "Lismore, NSW",
  },
  {
    cat: "Preservatives", slug: "bht", name: "Butylated Hydroxytoluene (BHT)",
    sub: "Synthetic antioxidant. Prevents oxidative rancidity in fats, oils, and rendered products.",
    weight: "20 kg pail", batch: "BH-26-01", image: "/assets/photos/products/bht.png",
    description: "Butylated hydroxytoluene (BHT) is a synthetic antioxidant used to prevent oxidative rancidity in fats, oils, and rendered products. It extends the shelf life of products containing animal fats by inhibiting the chain reaction of lipid oxidation. Commonly used in lard, tallow, and rendered cooking fats, as well as in the fat component of processed meat products. Supplied in a sealed 20 kg food-grade pail.",
    ingredients: "Butylated hydroxytoluene (100%).",
    formats: ["20 kg food-grade pail"],
    storage: "Store in a cool, dry place away from heat sources. Keep sealed when not in use.",
    curing: "N/A — antioxidant",
    origin: "Lismore, NSW",
  },
  {
    cat: "Preservatives", slug: "propylparaben", name: "Propylparaben",
    sub: "Antimicrobial preservative for meat, dairy, and bakery. Effective across a wide pH range.",
    weight: "20 kg pail", batch: "PB-26-02", image: "/assets/photos/products/propylparaben.png",
    description: "Propylparaben is an antimicrobial preservative effective across a wide pH range, used in meat, dairy, and bakery applications. It inhibits mould and yeast growth and is trusted by food manufacturers worldwide for its long track record of safety and efficacy. Particularly useful where product pH varies or where other preservatives lose effectiveness. Supplied in a sealed 20 kg food-grade pail.",
    ingredients: "Propylparaben (100%).",
    formats: ["20 kg food-grade pail"],
    storage: "Store in a cool, dry place. Keep sealed when not in use.",
    curing: "N/A — antimicrobial preservative",
    origin: "Lismore, NSW",
  },
];
